// ═══════════════════════════════════════════════════════════════════
// FILE:     user_dto.dart
// LAYER:    data/remote (Data Transfer Object)
// PURPOSE:  Mirrors the exact JSON shape returned by the /users endpoint.
//
// PLAIN ENGLISH:
//   When the server sends us JSON like {"id": 1, "name": "Leanne", ...},
//   Dart needs a class whose fields match that JSON exactly. That's a DTO.
//   We NEVER use DTOs in the UI — we convert them to domain models first.
//   That way, if the server changes its JSON shape, only this file and
//   its mapper need updating — the rest of the app is unaffected.
//
// WHO CREATES ME:
//   json_serializable generates the `fromJson` factory from this class.
//   Retrofit uses that factory to parse API responses automatically.
//
// WHO USES ME:
//   UsersRepositoryImpl receives me from the API, then maps me to User.
//
// WHAT I TALK TO:
//   Nothing — I'm a passive data container.
//
// I MATCH THE JSON SHAPE FROM:
//   GET https://jsonplaceholder.typicode.com/users
//   Response: [{"id": 1, "name": "...", "email": "...", "phone": "..."}]
// ═══════════════════════════════════════════════════════════════════

import 'package:freezed_annotation/freezed_annotation.dart';

part 'user_dto.freezed.dart';
part 'user_dto.g.dart';

// ┌─ WHY DTOs EXIST ─────────────────────────────────────────────
// │ The server can change its JSON shape at any time. If we used
// │ that shape directly in our UI, every API change would force
// │ a UI change. The DTO is a "translation layer" — it absorbs
// │ the server's shape, then a Mapper converts it into our own
// │ stable domain model. UI never imports DTOs.
// └──────────────────────────────────────────────────────────────

/// Data Transfer Object matching the JSON shape from /users endpoint.
///
/// PLAIN ENGLISH: a 1:1 mirror of the server's JSON. The `fromJson`
/// factory (generated by json_serializable) parses JSON into this class.
///
/// Called by: Retrofit deserializes API responses into this.
/// Calls: nothing.
@freezed
class UserDto with _$UserDto {
  const factory UserDto({
    required int id,
    required String name,
    required String email,
    required String phone,
  }) = _UserDto;

  /// Deserializes a JSON map into a [UserDto].
  ///
  /// PLAIN ENGLISH: takes a `Map<String, dynamic>` (Dart's version of
  /// a JSON object) and creates a UserDto from it. Generated by
  /// json_serializable — you never write this by hand.
  factory UserDto.fromJson(Map<String, dynamic> json) =>
      _$UserDtoFromJson(json);
}
